### ISSUE TITLE
Spicetify WebNowPlaying.js extension not connecting to Rainmeter whilst WebNowPlaying companion for both firefox and chrome have no problem

### ISSUE THREAD

**Issue by potatohub741** [khanhas/spicetify-cli#983]
## ℹ Computer information

- Spotify version: 1.1.62.583.gdac868ed-a
- Spicetify version: 2.5.0-itsmeow-patch4

## 📝 Provide detailed reproduction steps (if any)

1. Install spotify version 1.1.62.583.gdac868ed-a and close window
2. Create folder "Update" in %localappdata%\spotify and remove all groups in permissions 
3. Run "Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/khanhas/spicetify-cli/master/install.ps1" | Invoke-Expression" in PowerShell window
4. Run command "spicetify"
5. Run command "spicetify backup apply enable-devtool"
6. Close spotify
7. Run command "spicetify config extensions webnowplaying.js"
8. Run command "spicetify apply"
9. Install latest version of rainmeter (beta) as well as the JaxCore3 skin and ModularPlayers skin
10. Using the JaxCore3 settings, navigate to the ModularPlayers settings and switch "media" to Spotify (which uses the spicetify webnowplaying.js extension)

### ✔️ Expected result

ModularPlayers skin should display the currently playing spotify song and song information.

### ❌ Actual result

Plugin remains unchanged.
**NOTE 1:** When webnowplaying chrome or firefox extension is used instead, the ModularPlayers skin works fine and displays the information correctly (including the web version of spotify)
**NOTE 2:** I have tried other Rainmeter skins that utilise spicetify and its webnowplaying.js extension and they don't work either.
**NOTE 3:** Using the dev tools in spotify, under the "sources" tab, under the "extensions" drop-down menu, webnowplaying.js is listed.

## 📷 Screenshots

![image](https://user-images.githubusercontent.com/32790540/130033253-9678fae4-3485-4a09-9891-3c28408fca4e.png)
![image](https://user-images.githubusercontent.com/32790540/130033496-ea183d38-d9bb-4fe5-89d7-905022e69d2e.png)
![image](https://user-images.githubusercontent.com/32790540/130033634-2ac6283a-f310-4ffb-811c-5f506ca262f6.png)

**Comment by Fosmos** [comment]
Hmm the plugin still works for me. Have you checked the Rainmter Log while debug mode is on?

**Comment by itsmeow** [comment]
This is because the getProgress method has broken again. I've fixed it locally but there are also CSS mappings to update that Spicetify needs to work again.

**Comment by potatohub741** [comment]
> 
> 
> Hmm the plugin still works for me. Have you checked the Rainmter Log while debug mode is on?
> I'm running this version of spotify: 1.1.66.578.gc54d0f69-a (which I think is the latest)

Yeah I thought I might see something in the rainmeter logs, but there are no errors that I can see.
![image](https://user-images.githubusercontent.com/32790540/130447017-e787d87a-f27c-4753-ad8d-878eea7eab94.png)
This is a log I just took of me opening spotify (spicetify), refreshing the ModularPlayers skin and pressing the play/pause button a couple times. I thought it might be a firewall issue, but I disabled my firewall and made exceptions for both spotify and rainmeter. I also thought there might be some server that spicetify or something has to communicate with that my ISP might be blocking, so I tried using mobile hotspot which didn't work either.

@itsmeow does the issue with the getProgress method mean that the skin fails to get all the song information? I'd understand if it at least had the song name, or the song cover, and just the progress meter was faulty, but literally nothing is displayed when spotify is playing a song.
![image](https://user-images.githubusercontent.com/32790540/130447566-83ef9eb2-4006-4e57-baea-c993c2b9c894.png)

**Comment by Fosmos** [comment]
That's really odd because progress is working for me
![image](https://user-images.githubusercontent.com/59673626/130448832-2d6805cf-8349-4c9e-ba42-9fb6436698d6.png)

Try this skin: https://github.com/Fosmos/Simply.
Right click it and head to it's settings menu and make sure you have Spotify (WebNowPlaying) selected

**Comment by potatohub741** [comment]
@Fosmos I tried your skin, but with the webnowplaying mode selected it still doesn't work either : (
It is able to grab the song title and artist in the other spotify mode. In the webnowplaying mode the play/pause, skip forward/back dont work either (I assume they're coded through webnowplaying to communicate with webnowplaying in spicetify)

**Comment by Fosmos** [comment]
That's soooo weird. Everything (I mean everything) works perfectly for me. I can try your skin if you want. I'm literally stumped. One thing you can try is downloading the spiceitfy update's zip, extracting it and replacing everything in the spiceitfy-cli directory with everything in the expanded zip. Doubt it'll do anything, but 🤷🏻‍♂️  and then I guess while you're at it, double check you have webnowplaying.js properly set in the config file.

**Comment by potatohub741** [comment]
I'm not 100% if this is the right link because the modular players skin was installed through another skin that manages skins called JaxCore. 
[https://github.com/EnhancedJax/-JaxCore/releases/tag/v00030](url)
This should be the link, but if not, then just look around the releases. You also have to install another thing called MagicMeter or something for modularplayers, but it should prompt you when you try to install modularplayers using JaxCore3.

Where could I find the spicetify update zip? And yeah I do have webnowplaying.js installed in spicetify.
![image](https://user-images.githubusercontent.com/32790540/130617976-ea3c912a-410f-46f4-a215-944fb11e6d44.png)
I also just recently updated to spicetify v2.6.0 from the 2.5 meowpatch version which did nothing unfortunately : (

The funny thing is, it works perfectly fine when I use the webnowplaying extension in chrome or firefox. Even if I use the web version of spotify in those browsers. It's just the spotify client itself with spicetify that doesn't seem to link to webnowplaying in rainmeter.

**Comment by Fosmos** [comment]
https://github.com/khanhas/spicetify-cli/releases
Here's where you get the latest

**Comment by Fosmos** [comment]
Also I was able to get one of the Jax skins to work
![image](https://user-images.githubusercontent.com/59673626/130623730-de96781e-e3df-45bd-a4e6-2677718df254.png)

**Comment by potatohub741** [comment]
Do the other skin themes not work?

**Comment by Fosmos** [comment]
Yeah they all work
![image](https://user-images.githubusercontent.com/59673626/130624329-1a2fb893-69ae-49b9-b4c0-ccda40fc4a9a.png)

**Comment by potatohub741** [comment]
Are you running this version of spicetify?
![image](https://user-images.githubusercontent.com/32790540/130624754-bd803d56-8f7c-4161-823a-e7594e2646a2.png)

**Comment by Fosmos** [comment]
Yea I am, but I copied pasted the stuff from the zip, so my guess is they forgot to update the versioning

**Comment by potatohub741** [comment]
Do you think any of this might be an issue if spicetify's webnowplay.js is looking for where rainmeter is installed?
![image](https://user-images.githubusercontent.com/32790540/130625488-b9c5acaf-96c3-4cd1-b1c7-6bda23f183fd.png)

**Comment by Fosmos** [comment]
We have the same paths except for the ones with 'X'

**Comment by uppercrust3** [comment]
I'm having the same issue as potatohub, and my visualizer is completely broken on both web player and desktop app.

**Comment by potatohub741** [comment]
I have tried reinstalling spicetify again. Didn't work.
I have tried uninstalling and reinstalling an older version of spotify (1.1.61.583.gad060c66-a). Didn't work.
I have tried moving my rainmeter main install onto my primary hard drive. Didn't work
I have tried uninstalling and reinstalling the rainmeter webnowplaying plugin. Didn't work.

For some reason, the chrome and firefox webnowplaying plugins work absolutely fine with rainmeter. I've really run out of ideas on how I can debug this.

The only thing I can think of right now is that maybe the playing data webnowplaying.js collects through spicetify is saved to some local folder somewhere, and spicetify/spotify doesn't have permissions to write to that folder, so when Rainmeter's webnowplaying plugin goes to grab that data, there's nothing there to grab. 
I assume if this was the case, then the chrome and firefox versions of webnowplaying save their data to a different folder, and therefore wouldn't run into the same issue. Does this sound plausible?

**Comment by potatohub741** [comment]
![image](https://user-images.githubusercontent.com/32790540/130745557-53e191ba-f671-4215-b4ce-f775667147e8.png)
I looked at the spicetify devtools console and these errors were appearing. Could this have anything to do with spicetify not communicating with rainmeter?

**Comment by Fosmos** [comment]
Can you see where in the source code those problems are being hit?

**Comment by potatohub741** [comment]
I gave that a go, and when looking at the dev tools console in spotify, I can now see this error.
![image](https://user-images.githubusercontent.com/32790540/131215855-97401f57-f233-4e87-a3e5-ae3501dc973e.png)

Points to this line:
![image](https://user-images.githubusercontent.com/32790540/131215866-5d700408-d2cd-4bec-bef5-38e3bbc37f24.png)

Is `sp://...` a local storage space or some network connection? 
Just as I was typing this, I got more error messages.
![image](https://user-images.githubusercontent.com/32790540/131215900-5fa481a0-7cb1-4560-82f0-7459b61ed440.png)
Leading to these lines:
![image](https://user-images.githubusercontent.com/32790540/131215920-8c42dbef-7429-4df3-8c98-1a0a86ef654e.png)

**Comment by Fosmos** [comment]
Hmm interesting. I feel like the whole caching system isn't working great right now. So maybe comment out line 49?

**Comment by potatohub741** [comment]
Does that mean I won't be able to get the album art working for the rainmeter skin?

**Comment by Fosmos** [comment]
Not sure actually. The js usually gets the link to the album art which is basically a request to Spotify's servers, then it downloads it. Sometime ago I was trying to figure out how to get album art to work when Spotify was offline but couldn't so I don't think it's caching right now anyways

**Comment by potatohub741** [comment]
I imagine that webnowplaying.js in spicetify just copies/retrieves the album art from spotify's cache after spotify itself downloaded all the song data for the current playing song. So if spotify is fine with grabbing the album art, there must be something wrong with how webnowplaying.js grabs that data from spicetify. It looks like the script opens something called a WebSocket (I have no idea what it is tbh) and tries to store the album art in that location, but can't access that location (which you can sort of see in the errors in the images I sent before). Could it maybe be some sort of network blocking issue on my end?

**Comment by potatohub741** [comment]
It is very weird how it seems like it's just me (or only a few people) who are experiencing this problem, but thank you for your help! The alert() thing really helped me find where the code was stopping so I could comment it out, which seems to be a good bandaid fix for now.

**Comment by Fosmos** [comment]
Version 2.6.1 was just released. It doesn't touch webnowplaying.js but who knows maybe it'll fix something 🤷🏻‍♂️

**Comment by TheGeeKing** [comment]
Spicetify 2.6.1 is just a first fix for Spotify 1.1.66 and later, for extensions and custom apps. I would suggest to stay on 2.6 as the Ui is buggy with 2.6.1  extensions and custom apps

**Comment by TheGeeKing** [comment]
Spicetify 2.6.1 is just a first fix for Spotify 1.1.66 and later, for extensions and custom apps. I would suggest to stay on 2.6 as the Ui is buggy with 2.6.1  extensions and custom apps

**Comment by GrandArc** [comment]
> It is very weird how it seems like it's just me (or only a few people) who are experiencing this problem, but thank you for your help! The alert() thing really helped me find where the code was stopping so I could comment it out, which seems to be a good bandaid fix for now.

I actually have the same problem, my Rainmeter WebNowPlaying hasn't been working for a while and only today I tried to find the fix for the issue again. I had the exact same issue where the code couldn't get past if (!Spicetify.CosmosAsync || !Spicetify.Platform).

Used your band-aid idea to comment out the return function. It worked now, but like you said, the album art wouldn't appear on the Rainmeter skin which makes it much uglier than it usually look like :(

**Comment by Eden333** [comment]
> > It is very weird how it seems like it's just me (or only a few people) who are experiencing this problem, but thank you for your help! The alert() thing really helped me find where the code was stopping so I could comment it out, which seems to be a good bandaid fix for now.
> 
> I actually have the same problem, my Rainmeter WebNowPlaying hasn't been working for a while and only today I tried to find the fix for the issue again. I had the exact same issue where the code couldn't get past if (!Spicetify.CosmosAsync || !Spicetify.Platform).
> 
> Used your band-aid idea to comment out the return function. It worked now, but like you said, the album art wouldn't appear on the Rainmeter skin which makes it much uglier than it usually look like :(

same here, I commented out the first return, and it would work, besides not loading the cover. I had the patch4 thingy from someone who had linked it, idk if that matters.

**Comment by TheSolly** [comment]
Thanks @potatohub741 for pointing the issue and your effort to fix, I had the same issue and was looking for a solution...
I've build upon you work and found the culprit. Which was that `Spicetify` object doesnt have a `Platform` method anymore! That caused the whole Module to break!
I've modified the `webnowplaying.js` to fix this issue, at least for now.
The below is working now with latest spotify and spicetify and ModularPlayer skin

```
// NAME: WebNowPlaying Companion
// AUTHOR: khanhas (based on https://github.com/tjhrulz/WebNowPlaying-BrowserExtension)
// DESCRIPTION: Get song information and control player

/// <reference path="../globals.d.ts" />

(function WebNowPlaying() {
  // removed the Spicetify.Platform check as Spicetify doesnt contain a Platform method anymore!
  if (!Spicetify.CosmosAsync) {
    setTimeout(WebNowPlaying, 500);
    return;
  }

  let currentMusicInfo;
  let ws;
  let currState = 0;
  const storage = {};
  function updateStorage(data) {
    if (!data?.track?.metadata) {
      return;
    }
    const meta = data.track.metadata;
    storage.TITLE = meta.title;
    storage.ALBUM = meta.album_title;
    storage.DURATION = convertTimeToString(parseInt(meta.duration));
    storage.STATE = !data.is_paused ? 1 : 2;
    storage.REPEAT = data.options.repeating_track
      ? 2
      : data.options.repeating_context
      ? 1
      : 0;
    storage.SHUFFLE = data.options.shuffling_context ? 1 : 0;
    storage.ARTIST = meta.artist_name;
    let artistCount = 1;
    while (meta["artist_name:" + artistCount]) {
      storage.ARTIST += ", " + meta["artist_name:" + artistCount];
      artistCount++;
    }
    if (!storage.ARTIST) {
      storage.ARTIST = meta.album_title; // Podcast
    }
    // Spicetify doesnt contain a Platform method anymore!
    // Spicetify.Platform?.LibraryAPI.contains(data.track.uri).then(
    //   ([added]) => (storage.RATING = added ? 5 : 0)
    // );

    const cover = meta.image_xlarge_url;
    if (cover?.indexOf("localfile") === -1) {
      storage.COVER =
        "https://i.scdn.co/image/" +
        cover.substring(cover.lastIndexOf(":") + 1);
    } else {
      storage.COVER = "";
    }
  }

  Spicetify.CosmosAsync.sub("sp://player/v2/main", updateStorage);

  function updateInfo() {
    if (!Spicetify.Player.data && currState !== 0) {
      ws.send("STATE:" + 0);
      currState = 0;
      return;
    }

    storage.POSITION = convertTimeToString(Spicetify.Player.getProgress());
    storage.VOLUME = Math.round(Spicetify.Player.getVolume() * 100);

    for (const field in storage) {
      try {
        const data = storage[field];
        if (data !== undefined && currentMusicInfo[field] !== data) {
          ws.send(`${field}:${data}`);
          currentMusicInfo[field] = data;
        }
      } catch (e) {
        ws.send(`Error:Error updating ${field} for Spotify Desktop`);
        ws.send("ErrorD:" + e);
      }
    }
  }

  function fireEvent(event) {
    const m = event.data;
    const n = m.indexOf(" ");
    let type = n === -1 ? m : m.substring(0, n);
    type = type.toUpperCase();
    const info = m.substring(n + 1);

    switch (type) {
      case "PLAYPAUSE":
        Spicetify.Player.togglePlay();
        break;
      case "NEXT":
        Spicetify.Player.next();
        break;
      case "PREVIOUS":
        Spicetify.Player.back();
        break;
      case "SETPOSITION":
        Spicetify.Player.seek(parseInt(info) * 1000);
        break;
      case "SETVOLUME":
        Spicetify.Player.setVolume(parseInt(info) / 100);
        break;
      case "REPEAT":
        Spicetify.Player.toggleRepeat();
        break;
      case "SHUFFLE":
        Spicetify.Player.toggleShuffle();
        break;
      case "RATING":
        const like = parseInt(info) > 3;
        const isLiked = storage.RATING > 3;
        if ((like && !isLiked) || (!like && isLiked)) {
          Spicetify.Player.toggleHeart();
        }
        break;
      case "TOGGLETHUMBSUP":
        if (!(storage.RATING > 3)) {
          Spicetify.Player.toggleHeart();
        }
        break;
      case "TOGGLETHUMBSDOWN":
        if (storage.RATING > 3) {
          Spicetify.Player.toggleHeart();
        }
        break;
    }
  }

  (function init() {
    ws = new WebSocket("ws://127.0.0.1:8974/");
    let sendData;

    ws.onopen = () => {
      ws.send("PLAYER: Spotify Desktop");
      currState = 1;
      currentMusicInfo = {};
      sendData = setInterval(updateInfo, 500);
    };

    ws.onclose = () => {
      clearInterval(sendData);
      setTimeout(init, 2000);
    };

    ws.onmessage = fireEvent;
  })();

  window.onbeforeunload = () => {
    ws.onclose = null; // disable onclose handler first
    ws.close();
  };

  /**
   * Zero padding a number
   * @param {number} number number to pad
   * @param {number} length
   */
  function pad(number, length) {
    var str = String(number);
    while (str.length < length) {
      str = "0" + str;
    }
    return str;
  }

  /**
   * Convert seconds to a time string acceptable to Rainmeter
   * @param {number} timeInMs
   * @returns {string}
   */
  function convertTimeToString(timeInMs) {
    const seconds = Math.round(timeInMs / 1000);
    const minutes = Math.floor(seconds / 60);
    if (minutes < 60) {
      return `${minutes}:${pad(seconds % 60, 2)}`;
    }
    return `${Math.floor(minutes / 60)}:${pad(minutes % 60, 2)}:${pad(
      seconds % 60,
      2
    )}`;
  }
})();

```

**Comment by GrandArc** [comment]
Can confirm the code above works! Thank you very much!! :)

**Comment by itsmeow** [comment]
@TheSolly The Platform hook has broken, I'm working on reimplementing it but the entire format changed again.

**Comment by TheSolly** [comment]
@itsmeow make sense now, thanks for letting us know!
Let me know if i could be of any help 🙏

**Comment by potatohub741** [comment]
I just tried your fix, and I'm glad to say it worked perfectly! Thanks for everyone's help!

**Comment by Eden333** [comment]
Works again!

**Comment by afonsojramos** [comment]
I'm going to close this issue as it has been fixed on master as well. Thanks @TheSolly !

**Comment by TheSolly** [comment]
We got a different issue with the latest updates!

![Screenshot 2021-09-16 204538](https://user-images.githubusercontent.com/31882844/133667989-d73bb695-c8f7-4a25-a56f-c22ad1ab744f.png)


debugged, and the culprit was a change in the structure of the `Player` hook, made a temp fix:

had to change `getProgress` inside the `spicetifyWrapper` 

``` javascript
getProgress: () =>
      (Spicetify.Player.origin._state.isPaused ? 0 : Date.now() - Spicetify.Player.origin._state.timestamp) + 
       Spicetify.Player.origin._state.positionAsOfTimestamp,
```

**Comment by itsmeow** [comment]
@TheSolly Thanks, this is on 1.1.68, right? I haven't been able to fix methods like getProgress because my client hasn't pulled the update. Can you verify that implementation works on Spotify 1.1.68 (File -> Help -> About Spotify)?

**Comment by TheSolly** [comment]
Yup Spotify is on latest version 👌

**Comment by TheSolly** [comment]
Do you want me to open a PR?

**Comment by TheGeeKing** [comment]
Thanks for the help! Don't need to, I think it should be good. 🙂

**Comment by afonsojramos** [comment]
@TheSolly please do!

**Comment by TheSolly** [comment]
#1065 👍
